# Generated by Django 3.2.8 on 2021-11-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('area_atuacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='livro',
            name='escritor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.escritor'),
        ),
    ]
