# Generated by Django 3.2.8 on 2021-11-09 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211109_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='estante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estante'),
        ),
    ]
