# Generated by Django 3.2.8 on 2021-11-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211109_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
