# Generated by Django 3.2.8 on 2021-11-12 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_emprestimo_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.livro'),
        ),
    ]
